### ISSUE TITLE
Manual trade entry: 1 day lag

### ISSUE THREAD

**Issue by brouneau** [GeneBO98/tradetally#60]
This app is really nice, thank you for making it :) One bug I have is when entering manual trades, the date gets shifted from 1 day when we go back to the trade list.

New Trade / Edit Trade
<img width="761" height="307" alt="Image" src="https://github.com/user-attachments/assets/b7043a42-72f6-44b4-84a2-730bd25a826c" />

Trade list

<img width="861" height="66" alt="Image" src="https://github.com/user-attachments/assets/33c3f964-57aa-45d2-b548-1517b16e0425" />

The date should be October 10th, not 9th.

Let me know if you need more information, thx.

**Comment by Alli7777** [comment]
@brouneau Yes, I have the same issue. @GeneBO98 Can this be fixed? In my Profile I have "Eastern Time" selected.

**Comment by GeneBO98** [comment]
This was an issue that was previously fixed. If you are using docker compose make sure to do a docker compose pull for the latest updates.

**Comment by GeneBO98** [comment]
I just pushed a new version to latest as well as for tag v2.1.0 and it will be ready in a few minutes.

**Comment by brouneau** [comment]
Hmmm that is strange, I'm on v2.1.0, with the new Options feature (nice addon btw).
My timezone is Eastern Time, but still get the 1-day lag when manually creating Trade entries.

**Comment by GeneBO98** [comment]
Okay. I have not been able to replicate the problem in the latest version. I will change how dates are handled and push them out again

**Comment by brouneau** [comment]
Great thank you!
