### ISSUE TITLE
Post-Market Reflection in Templates

### ISSUE THREAD

**Issue by electricar** [GeneBO98/tradetally#68]
Thank you for the diary and playbook templates!

I noticed that you implemented a template field for every field except "Post-Market Reflection".
Would it be possible to add this field as well?

Thank you very much in advance.

**Comment by GeneBO98** [comment]
I will get that added in the next commit.

**Comment by GeneBO98** [comment]
Added support in commit 9306ac87bbcc16d02245f8177a330704bfa028ed

**Comment by electricar** [comment]
I cannot save anything in the "Post-Market Reflection" field.
If I save the template and open it again, the "Post-Market Reflection" field is empty.
Also I cannot make changed to existing templates.
When I click "Save template" the template view stays open.
When I close the template through "cancel" or clicking outside the template and open it again, the change was not saved.

**Comment by GeneBO98** [comment]
Okay, I tested and believe this is fixed in the latest commit.

**Comment by electricar** [comment]
I just tested this with the latest commit and I am still not able to update an existing template.

**Comment by GeneBO98** [comment]
@electricar do you get an error when you try? In my test environment I can make edits to the templates alright

**Comment by electricar** [comment]
No error, I click on "save template" (if I remember correctly the naming) but nothing happens. The window stays open. The go out of the editing window I have to click cancel or outside the window, but the changes were not saved.

**Comment by GeneBO98** [comment]
Hmm, can you see if what your developer tools say in the console. You can usually press F12 and check for any errors. Potentially look for errors in your docker logs as well.

**Comment by electricar** [comment]
Here is what I am getting in the browser console (Firefox):
<img width="1390" height="1213" alt="Image" src="https://github.com/user-attachments/assets/a9308b5c-0e18-4459-9ee2-f9e4552234fd" />

**Comment by GeneBO98** [comment]
Okay, in the latest commit I added more verbose logging to the templates so hopefully you will be able to see that in your docker logs

**Comment by electricar** [comment]
Here we go:

<img width="937" height="1129" alt="Image" src="https://github.com/user-attachments/assets/eeee6830-2115-4704-b633-c1f170d3a669" />

<img width="1234" height="1188" alt="Image" src="https://github.com/user-attachments/assets/c34f13f0-af36-448b-a222-5bef8da30214" />

**Comment by GeneBO98** [comment]
Try it after latest.  Should be ready in a few minutes once it builds

**Comment by electricar** [comment]
yes it's working, thank you! :)
